### ISSUE TITLE
Remove unused resources

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/k8s-config#6]
e.g.: https://github.com/woog-life/k8s-config/blob/master/templates/twitter-secrets.yaml are deployed by the [tweeter](https://github.com/woog-life/tweeter): https://github.com/woog-life/tweeter/blob/master/templates/secret-twitter.yml

Without this change the deployment will not work due to potential resource conflicts (helm won't deploy a resource which is already deployed by another chart/manually).

**Comment by BjoernPetersen** [comment]
I honestly haven't even looked at the errors we're currently getting. So I'm doing my part.

**Comment by torbencarstens** [comment]
me neither :shrug:
